[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect - this is crucial for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable camera access for the app
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(self), microphone=()"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
